title: Hi! My name is Jacob & I'm learning GitHub \:boom:\
author: Jacob Pettit
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My first GitHub pages blog!

# social links
twitter_username: NFTeezuz # DO NOT include the @ character, or else the build will fail!
github_username:  JacobSPettit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima